config/routes.rb
Rails.application.routes.draw do
  root to: 'wagoners#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :wagoners do
    member do                             # member => restaurant id in URL
      get 'wag_show'                          # RestaurantsController#chef
    end
    resources :bookings, only: [ :index, :new, :create]
  end
  # resources :users, only: [ :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :wagoner

  validates :start_at, presence: true

  validate :start_at_cannot_be_in_the_past, :end_at_cannot_be_greater_than_checkout

private
  def start_at_cannot_be_in_the_past
    if self.start_at < Date.today
      errors.add(:start_at, "Can't be in the past")
    end
  end

  def end_at_cannot_be_greater_than_checkout
    if self.start_at > self.end_at
      errors.add(:end_at, "Checkout must be greater than start at")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :bookings
  has_many :wagoners
  validates :first_name, presence: true
  validates :last_name, uniqueness: true, presence: true
  mount_uploader :photo, PhotoUploader
end

app/models/wagoner.rb
class Wagoner < ApplicationRecord
  belongs_to :user
  has_many :users
  has_many :bookings
  validates :description, presence: true
  validates :github_name, uniqueness: true, presence: true
  validates :price, presence: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  mount_uploader :avatar, PhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?


  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  #skip_before_action :authenticate_user!, only: :index

  def index

    # @wagoner = Wagoner.find(params[:wagoner_id])
    @bookings = Booking.where(user: current_user)

  end

  # def new
  #   @wagoner = Wagoner.find(params[:wagoner_id])
  #   @booking = Booking.new
  # end

  # def show
  # end

  def create
    @wagoner = Wagoner.find(params[:wagoner_id])
    @booking = Booking.new(booking_params)
    @booking.wagoner = @wagoner
    @booking.user = current_user

    if @booking.save
      flash[:notice] = ""
      redirect_to wagoner_bookings_path(@wagoner)
    else
      flash[:notice] = "NOOOOOOOOOOOON"
      redirect_to wagoner_path(@wagoner)
    end
  end

  def booking_params
    params.require("booking").permit(:start_at, :end_at)
  end
end

app/controllers/wagoners_controller.rb
class WagonersController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  before_action :find_wagoner, only: [:show, :edit, :update, :delete]

  def index
    @wagoners_list = Wagoner.all
    @wagoners = Wagoner.where.not(latitude: nil, longitude: nil)
    @markers = @wagoners.map do |wagoner|
      {
        lat: wagoner.latitude,
        lng: wagoner.longitude,
        infoWindow: render_to_string(partial: "infowindow", locals: { wagoner: wagoner }),
        image_url: helpers.asset_url('logo_wagoner.png')
      }
    end
  end

  def show
    @wagoner = Wagoner.find(params[:id])
    @booking = Booking.new
        @markers =
      [{
        lat: @wagoner.latitude,
        lng: @wagoner.longitude,
        infoWindow: render_to_string(partial: "infowindow", locals: { wagoner: @wagoner }),
        image_url: helpers.asset_url('logo_wagoner.png')
      }]
  end

  def wag_show
    @wagoner = Wagoner.find(params[:id])
    # @wagoners = Wagoner.where.not(latitude: nil, longitude: nil)
    @markers =
      [{
        lat: @wagoner.latitude,
        lng: @wagoner.longitude,
        infoWindow: render_to_string(partial: "infowindow", locals: { wagoner: @wagoner }),
        image_url: helpers.asset_url('logo_wagoner.png')
      }]

  end

  def new
    @wagoner = Wagoner.new
  end

  def create
    @wagoner = Wagoner.new(wagoner_params)
    if @wagoner.save
      redirect_to wag_show_wagoner_path(@wagoner)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @wagoner.update(wagoner)
  end

  def delete
    @wagoner.destroy
  end

  private

  def find_wagoner
    @wagoner = Wagoner.find(params[:id])
  end

  def wagoner_params
    params.require(:wagoner).permit(:description, :github_name, :price, :user_id, :rating, :avatar, :address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def display_stars(stars_number)
   ("<i id='stars' class='fas fa-star'></i>" * stars_number + "<i class='far fa-star'></i>" * (5 - stars_number)).html_safe if !stars_number.nil?
  end
end

app/views/bookings/index.html.erb
<div class="container">
  <h1 class="dashboard"> Ton Dashboard 😎</h1>
  <h5 class="description">Tu trouveras ci-dessous tous tes petits rendez-vous galants :</h5>
  <div class="flash flash-success alert alert-dismissible fade show" role="alert">
    <% if @bookings.any? %>
      <span><strong>Yay!</strong> 🎉 Vous avez loué <%= @bookings.last.wagoner.github_name %></span>
      <a data-dismiss="alert" aria-label="Close">
        <i class="fas fa-times"></i>
      </a>
      <% else %>
        <p>Tu n'as aucun petits rendez-vous, book en un ! 😍</p>
      <% end %>
  </div>

  <div>
    <% @bookings.each do |booking| %>
      <div>
        <div class="notification">
          <%= cl_image_tag(booking.wagoner.avatar, width:100)%>
          <div class="notification-content">
            <p><small><%= booking.wagoner.github_name %></small></p>
            <p>Réservation du <%= booking.start_at %> au <%= booking.end_at %></p>
          </div>

          <!-- <div class="notification-actions">
            <a href="#">Delete <i class="far fa-trash-alt"></i></a>
          </div> -->
        </div>
      </div>
    <% end %>
  </div>

  <div>
    <%= link_to "Retourner à l'accueil", root_path, class: 'card-link btn btn-primary' %>
  </div>

</div>

app/views/bookings/new.html.erb
<!-- <div class="container">
  <h1> Confirmation</h1>
  <div class="notification">
    <p>Félicitations ! vous avez loué <%= @wagoner.github_name %> pour quelques heures </p>
    <img src='https://kitt.lewagon.com/placeholder/users/arthur-littm' class="avatar-large"/>
    <div class="notification-content">
    </div>

  </div>
</div> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>My-Wagonner-renting</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%# render 'shared/flashes' %>
    <%= yield %>
      <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/shared/_banner.html.erb
<div class="banner" style ="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)),
url('https://images.unsplash.com/photo-1510146758428-e5e4b17b8b6a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2550&q=80');">


  <div class="container py-3">
      <h1>Wagoners te permet de créer <strong>de nouvelles relations</strong> dans <strong>la communauté des wagoneurs(euses)</strong>!</h1>
      <p>Rapproche toi des wagoners que tu préfères! 😉</p>
      <!-- <button class="btn btn-outline-light" href="#">Look for a wagoner</button> -->
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="flash flash-success alert alert-dismissible fade show" role="alert">
     🎉  <%= notice %>
    <a data-dismiss="alert" aria-label="Close">
      <i class="fas fa-times"></i>
    </a>
  </div>
<% end %>
<% if alert %>
  <div class="flash flash-warning alert alert-dismissible fade show" role="alert">
    <span><strong>Mmh</strong> 🤔 seems like you don't have <a href="#">profile picture</a> yet.</span>
    <a data-dismiss="alert" aria-label="Close">
      <i class="fas fa-times"></i>
    </a>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    © 2019 Wagoners, Inc. All rights reserved. <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">

  <%= link_to root_path, class: "navbar-brand" do %>
  <%= image_tag "https://res.cloudinary.com/dvb6zudlf/image/upload/v1558537440/logo_wagoner_kei7wi.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <!-- <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="">Sign in</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Mon dashboard</a>
      </li>
      <li class="nav-item dropdown">
        <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://kitt.lewagon.com/placeholder/users/ssaunier" />
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Log Out</a>
        </div>
      </li>
    </ul>
  </div> -->


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Devenir wagoner", new_wagoner_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Dashboard", wagoner_bookings_path(:wagoner_id), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Se deconnecter", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://res.cloudinary.com/wagon/image/upload/c_fill,g_face,h_200,w_200/zuoxgsu2nprklyrvnwzj.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Se connecter", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/wagoners/_infowindow.html.erb
<div class="wagoner-pop-up-info">
  <div class="card-image-map">
  <%= cl_image_tag(wagoner.avatar) %>
    <h3><%= link_to wagoner.github_name, wagoner_path(wagoner) %></h3>
    <p><%= wagoner.description %></p>
  </div>


  <p class="wagoner-pop-up-price"><%= wagoner.price%>€/H</p>
</div>

app/views/wagoners/edit.html.erb
<h1>Wagoners#edit</h1>
<p>Find me in app/views/wagoners/edit.html.erb</p>

app/views/wagoners/index.html.erb
<%= render 'shared/flashes' %>
<%= render 'shared/banner' %>

<div class="main-container">
  <div class="container my-3">

  <div class="row">
    <% @wagoners_list.each do |wagoner| %>
    <div class="col-4">
      <div>
        <!-- Element card -->

        <div class="card my-2">
          <div class="card-image-height">
            <%= cl_image_tag(wagoner.avatar) %>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= wagoner.github_name %></h5>
            <p class="card-text">
              <%= wagoner.description %>
            </p>
            <%= link_to "Plus de détails", wagoner_path(wagoner), class: 'card-link btn btn-primary' %>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>

</div>

  <div
  id="map"
  style="width: 100%;
  height: 600px; margin: 20px 0px; position: sticky; top: 0;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key = "<%= ENV['MAPBOX_API_KEY'] %>"
  >
</div>

</div>

app/views/wagoners/new.html.erb
<div class="container py-9">

<div class="form-signup">
  <h1>Inscription</h1>
  <br>
  <%= simple_form_for @wagoner do |f| %>
      <%= f.input :github_name %>
      <%= f.input :description %>
      <%= f.input :price %>
      <%= f.input :address %>
      <%= f.input :rating, :as => :hidden, default: 0 %>
      <%= f.input :user_id, :as => :hidden, :input_html => { :value => current_user.id }%>
      <%= f.input :avatar %>
      <%= f.input :avatar_cache, as: :hidden %>
      <br>
      <%= f.submit "Créer", class: "btn btn-primary btn-lg btn-block" %>
  <% end %>
  </div>
</div>
 

app/views/wagoners/show.html.erb
<div class="container">

<br>
  <div class="container mt-3">
    <h1>Louez-moi ! 🤗</h1>

    <div class="cards">
      <div class="card">
        <div class="card-image-product">
          <%= cl_image_tag(@wagoner.avatar) %>
        </div>
        <div class="card-body">

            <h2 class="card-title"><%= @wagoner.github_name %></h2>
            <p><strong>Description:</strong> <%= @wagoner.description%></p>
            <p><strong>Price:</strong> <%= @wagoner.price%>€/jour</p>
            <p><%= display_stars(@wagoner.rating) %></p></p>
          </div>
        </div>


        <div class="form-rent">
        <div class="form">

          <%= simple_form_for [@wagoner, @booking] do |f| %>
          <%= f.input :start_at, as: :string, required: false, input_html: {class: "datepicker"} %>
          <%= f.input :end_at, as: :string, required: false, input_html: {class: "datepicker"} %>
          <%= f.button :submit, "Je réserve mon wagoner", class: "btn btn-primary" %>
          <% end %>
          <div>
            <div
            id="map"
            style="width: 100%;
            height: 300px; margin: 0px 0px; position: sticky; top: 0;"
            data-markers="<%= @markers.to_json %>"
            data-mapbox-api-key = "<%= ENV['MAPBOX_API_KEY'] %>"
            >
          </div>
        </div>
        <br>
          <%= link_to "Revenir aux Wagoners", wagoners_path, class: "btn btn-outline-secondary btn-sm" %>
        </div>

      </div>

    </div>
  </div>

app/views/wagoners/wag_show.html.erb
<div class="container">
  <div class="container mt-3">

    <h1>Mon profil</h1>


    <div class="cards">

      <div class="card">
        <div class="card-image-product">
          <%= cl_image_tag(@wagoner.avatar) %>
        </div>
        <div class="card-body">

          <p class="card-text">
            <h2 class="card-title"><%= @wagoner.github_name %></h2>
            <p><strong>Description:</strong> <%= @wagoner.description%></p>
            <p><strong>Price:</strong> <%= @wagoner.price%>€/jour</p>
            <p><strong>Address:</strong> <%= @wagoner.address%></p>

          </div>
          <div>
            <div
            id="map"
            style="width: 100%;
            height: 300px; margin: 0px 0px; position: sticky; top: 0;"
            data-markers="<%= @markers.to_json %>"
            data-mapbox-api-key = "<%= ENV['MAPBOX_API_KEY'] %>"
            >
          </div>
        </div>
      </div>

    </div>
  </div>
</div>